---
- name: Install Nginx
  become: yes
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configure reverse proxy
  become: yes
  template:
    src: inkomoko_proxy.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - Restart Nginx

- name: Ensure Nginx is running
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes

