---
- name: Update apt cache and upgrade packages
  apt:
    update_cache: yes
    upgrade: dist
  become: yes

- name: Install dependencies
  apt:
    name:
      - wget
      - apt-transport-https
      - software-properties-common
    state: present
  become: yes

# ---------------------
# PROMETHEUS INSTALL
# ---------------------
- name: Create Prometheus user and directories
  become: yes
  shell: |
    useradd --no-create-home --shell /bin/false prometheus
    mkdir -p /etc/prometheus /var/lib/prometheus

- name: Download and install Prometheus
  become: yes
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes
    creates: /tmp/prometheus-2.52.0.linux-amd64

- name: Copy Prometheus binaries
  become: yes
  shell: |
    cp /tmp/prometheus-2.52.0.linux-amd64/prometheus /usr/local/bin/
    cp /tmp/prometheus-2.52.0.linux-amd64/promtool /usr/local/bin/
    cp -r /tmp/prometheus-2.52.0.linux-amd64/consoles /etc/prometheus
    cp -r /tmp/prometheus-2.52.0.linux-amd64/console_libraries /etc/prometheus
    cp /tmp/prometheus-2.52.0.linux-amd64/prometheus.yml /etc/prometheus/
    chown -R prometheus:prometheus /etc/prometheus /var/lib/prometheus /usr/local/bin/prometheus /usr/local/bin/promtool

- name: Create Prometheus systemd service
  become: yes
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
        --config.file /etc/prometheus/prometheus.yml \
        --storage.tsdb.path /var/lib/prometheus/ \
        --web.console.templates=/etc/prometheus/consoles \
        --web.console.libraries=/etc/prometheus/console_libraries

      [Install]
      WantedBy=default.target

- name: Reload systemd and start Prometheus
  become: yes
  shell: |
    systemctl daemon-reexec
    systemctl daemon-reload
    systemctl enable --now prometheus

# ---------------------
# GRAFANA INSTALL
# ---------------------
- name: Add Grafana APT key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  become: yes

- name: Add Grafana APT repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
  become: yes

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes
  become: yes

- name: Start and enable Grafana
  service:
    name: grafana-server
    enabled: yes
    state: started
  become: yes
