---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Upgrade all packages
  apt:
    upgrade: dist
  become: yes

- name: Install Java 17
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes
  become: yes

- name: Add Jenkins GPG key
  become: yes
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present

- name: Add Jenkins repository
  become: yes
  apt_repository:
    repo: 'deb https://pkg.jenkins.io/debian binary/'
    state: present

- name: Install Jenkins
  become: yes
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Start and enable Jenkins
  become: yes
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Check Jenkins service status
  become: yes
  command: systemctl status jenkins
  register: jenkins_status
  changed_when: false

- name: Print Jenkins status
  debug:
    var: jenkins_status.stdout_lines
